### ISSUE TITLE
Resume does not work: ERROR Unexpected exception: [Errno 17] File exists: '/home/loek/modernmt/engines/engdut/models/decoder'

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/modernmt#490]
loek@DORAEMON:~/modernmt$ ./mmt create en nl data/engdut -e engdut --resume --tensorboard-port 6006

=========== TRAINING STARTED ===========

ENGINE:   engdut
LANGUAGE: en > nl

(1/4) Cleaning corpora
    (1/6) Cleaning corpora...                                    DONE in 1m 8s
    (2/6) De-duplicate corpora...                                DONE in 5s
    (3/6) Preprocess corpora...                                  DONE in 34s
    (4/6) Creating aligner filter...                             DONE in 2m 15s
    (5/6) Scoring corpora...                                     DONE in 22s
    (6/6) Apply aligner-based filter...                          DONE in 1s
(1/4) Cleaning corpora DONE in 4m 27s
(2/4) Creating engine

ERROR Unexpected exception: [Errno 17] File exists: '/home/loek/modernmt/engines/engdut/models/decoder'

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 
how did you run the first time the command `mmt create`?

**Comment by LoekvanKooten** [comment]
Without -debug, I have to admit. Is that absolutely needed? Why not make that the default? Does it slow down the process?

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 

`--debug` does not slow down the training. It simply removes all temporary data generated during the process at the end of a successful training. We decided to let `--debug` an option (and not the default), because we do not want that an inattentive user complies for the disk consumption. just because it forgets to remove the temporary files.

Have you consider the possibility to start a new training using your model already trained?
In this case, you can use the option `--from-model`.

**Comment by LoekvanKooten** [comment]
Ah, --from-model sounds exactly like what I need! So what is the exact difference between --from-model and --resume?

**Comment by nicolabertoldi** [comment]
@LoekvanKooten 

- `--resume` should be used to continue a previous training on the same training data; in fact, it will force the training process to resume from the latest checkpoint, no matter how it stops before (either wrongly or successfully). It requires that the temporary data of the previous training is available, and this happens when the previous training was run with `--debug`.

- `--from-model` should be used to start a completely new training on (possibly new) training data, the training procedure initialises the model with that specified by the parameter. With respect to the standard training, there are two main differences: 
  - the initial model is already trained, and not randomly initialized
  - the vocabulary is not extended, but the one of the loaded model is exploited

**Comment by LoekvanKooten** [comment]
Thank you! All is clear now.
