### ISSUE TITLE
How to train MMT using centralized datastream in a Leader-Followers cluster?

### ISSUE THREAD

**Issue by tabulahussla** [modernmt/modernmt#500]
So I've set up a Leader-Followers cluster in AWS Kubernetes environment with nvidia-docker.
Next step is to train MMT sending parallel or TMX data into centralised datastream.
But how exactly this could be done?
I've tried using `kafka-console-producer.sh` from Kafka CLI to upload a TMX file into `memory-upload-stream` topic. That seem to have produced no effect.

```
root@modernmt-0:/tmp/kafka/kafka_2.12-2.3.0# bin/kafka-console-producer.sh --broker-list modernmt-0.modernmt:9092 \
>  --topic mmtDS-memory-upload-stream < Books/en-ru.tmx
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> # outputs a long line of ">>>"
```

This would be great to have a datastream usage example in the wiki.

**Comment by davidecaroselli** [comment]
Hi @tabulahussla 

I'm not sure if you are mixing two different concepts together, so let me try to explain.

First ModernMT requires a good, general-purpose, neural engine model that must be trained from scratch just like any other NN framework does. The main difference is that with ModernMT is way more simpler: just use the command `mmt create` (you can type `./mmt create --help` to have more infos). In this step ModernMT will use the GPUs on the single machine where you have started the command, so the cluster won't help much.

After you have the engines, and you correctly setup a ModernMT cluster, you can then upload TMXes or even single contributions in real-time, without the need of a re-training: ModernMT will be able to **adapt** on that new content right away. In order to add new contributions or memories you don't have to go too deep (Kafka level) but you have the ability do this in two ways:

- Command line: with commands like `mmt memory import` or `mmt memory add`, again you can use `--help` to print the instructions.
- Directly via REST API: with the [Create memory API](https://github.com/modernmt/modernmt/wiki/API-Create-Memory) and [Add to Memory API](https://github.com/modernmt/modernmt/wiki/API-Add-to-Memory)

**Comment by tabulahussla** [comment]
Wow that exactly what I needed to notice. I was unable to train MMT on NVIDIA Tesla GPU's with 8GiB RAM that I've rented from Amazon. So I thought clustering will be a solution. But my solution turned out to be a much more powerful setup with 16x NVIDIA Tesla GPUs with 12GiB RAM. With this setup training took only about 17 hours to be loosing around 0.001 per iteration in "loss". Isn't this amazing?
