### ISSUE TITLE
MMT 4.5.4 : XML-compliant output enforcement ?

### ISSUE THREAD

**Issue by EtienneAb3d** [modernmt/modernmt#533]
Hi !

Really nice to read: "Dramatically improved XML tag projection with XML-compliant output enforcement"

Can you explain a bit what is behind this?

Best regards,
Etienne

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d ,

sure: basically we spot a bug in the tag projection implementation that could result in a situation where the output tags were not XML-compliant anymore. Here's an example of the problem that we have now solved but that was still possible in previous versions:

**sentence**
```xml
One <b><a>Two</a></b> <c>Three</c>
```

**translation (previous version)***
```xml
Uno <b><a>Due</a> <c></b>Tre</c>
```

The translation was not valid anymore because of `<c></b>`.
