### ISSUE TITLE
Am I able to translate the same language?

### ISSUE THREAD

**Issue by hscspring** [modernmt/modernmt#536]
Hi, mmt:
as the title said, sometimes I just want to make some transfer that likes a "translation", src and tgt come from the same languages. Is it supported here? much tks.

**Comment by EtienneAb3d** [comment]
I had the same problem here: #442
As far as the behaviour is still the same in new releases:
- you can train and translate using country variants like "en-GB" => "en-US".
- BUT, the memory part of MMT, for the micro-live-tuning, is confused with this because it uses only the 2 first chars of the language code. So, you will be able to properly use MMT only without the use of a memory and the micro-live-tuning.
My solution was:
- use the good country code for the output, because MMT is using this country code to choose the final formatting rules. 
- use a wrong country code for the input, just to get a different one from the output. Try to use the code of a language as similar as possible to the good one.
- of course, you have to take this into account in the client part of your code.

**Comment by hscspring** [comment]
I've seen many your issues.:)
----
yep, that may be a proper solution, actually i just want to modify the source code~

**Comment by davidecaroselli** [comment]
Hi @hscspring 

the hint from @EtienneAb3d is actually the right thing to do. Unfortunately, it is not easy at the moment make ModernMT support same-language translations because in many parts of the code there is the assumption that it is possible to "identify" a parallel corpora source-to-target thanks to base language code (i.e. "en" or "fr").

**Comment by hscspring** [comment]
@davidecaroselli thanks a lot. I'm trying.
