### ISSUE TITLE
custom tags stripped in tokenized corpora

### ISSUE THREAD

**Issue by mzeidhassan** [modernmt/modernmt#541]
HI @davidecaroselli and @nicolabertoldi ,

I hope all is well with you and your beloved ones and you are well and safe. I am happy to see things are improving in Italy. Stay safe!

I have a question about custom tags. I created a tmx file with some custom tags surrounding some terms. 

Something like:

`<financialstart>accounts payable<financialend> `and I used the same tags in the target term.

By looking at the files at default/tmp/training/_temp_datagen/tokenized_corpora/ar__en/train

I see that all tags are stripped.

Can you please let me know how I can preserve such tags and protect them from stripping? I hope there is a way.

Thanks,
Mohamed

**Comment by mzeidhassan** [comment]
I also noticed the same is happening when I import the TMX into a memory.

**Comment by ecly** [comment]
Hello @mzeidhassan - since tags are stripped during inference and reinserted based on the attention distribution, it also makes no sense to include them during training, as they will be removed during inference anyways. From my knowledge you'd have to fork MMT and alter both its pre-processing for training, and it's pre/post-processing for inference, to get what you want, but I think you should make sure that you have a good reason for wanting to do so, instead of using the built-in tag processing functionality.

**Comment by mzeidhassan** [comment]
Thanks a million @ecly for your valuable feeds.

I actually was trying to experiment with this paper arxiv.org/pdf/1912.00567.pdf to see if using tags can handle terminology better.

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan 

if you just need tags to be as "metadata" for the translations, you already have the solution: use a custom identifier of your choice which is not an XML tag.
For example, you can use tokens such as `__financialstart__` or `[[financialstart]]`, they are not required to be actual XML.

As @ecly said, because ModernMT is XML-aware, the XML tags handling logic is very difficult to eradicate and/or change, because it is a fundamental feature of the engine. If you really want to use XML tags, you'll have to create your custom version of ModernMT starting from a fork of the project.
