### ISSUE TITLE
Nvidia limits crypto-mining on new graphics card

### ISSUE THREAD

**Issue by EtienneAb3d** [modernmt/modernmt#582]
Just read about this: https://www.bbc.com/news/technology-56114508

I wonder: is the performance drop-down due to this Nvidia limitation?

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d 

I don't think the two things are related: we run our tests on A100, which are the NVIDIA enterprise flagship GPUs for Ampere architecture, and for sure this model does not have any limitations. Yet, we observed the drop-down in performances on that hardware.

Moreover, we tried the new fairseq on the old 2080 GPUs, and we observed the same exact performance drop; so we are pretty sure that the cause of that issue is the new version of either fairseq or pytorch (or both) that introduce more overhead to the computation.
